### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Sija** [randomstate/jwt#1]
There's already a JWT shard maintained by @crystal-community: https://github.com/crystal-community/jwt

**Comment by byfoz** [comment]
Hey @Sija :)

A fair question! 
At the time of creation (very recently!) I looked at submitting a PR for the existing JWT package. I'm new to Crystal and was still bedding in with the OpenSSL RSA bindings I created etc, so it looked like more work than I wanted in order to figure out how the existing package worked and how to add RSA support to it.

The main issue was that there would likely need to be changes to the core parts of the API ('signing a JWT') and discussion on how to solve it to accommodate both HMAC signing and supplying an RSA key, and honestly I didn't have the time to worry about that as I've got a project I'm working on that needed it straight away, nor was I 100% confident that I would get a reasonable response from the maintainers since the other JWT package hasn't seen any major updates since the end of 2016.

It's not 100% ideal having RSA support in one shard and HMAC in another, but it's not a catastrophe either really. 

There are a few smaller reasons as well but it would be a big discussion in itself to explain them effectively.

Hope that helps, and feel free to suggest changes or incorporate the RSA parts of this package into the community-maintained shard.
